/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Personagem mago = new Personagem();
        int vida = Integer.parseInt(IO.readln("Entre com o valor da vida: "));
        mago.definirVida(vida);

        int mana = Integer.parseInt(IO.readln("Entre com o valor da vida: "));
        mago.definirMana(mana);

        int forca = Integer.parseInt(IO.readln("Entre com o valor da força: "));
        mago.definirForca(forca);
        IO.println("Vida: " + vida);
        IO.println("Mana: " + mana);
        IO.println("Força: " + forca);
    }
}
