/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.HashMap;

public class App {

    //(chave, valor) --- (isbn, livro)
    private HashMap<String, Livro> livros = new HashMap<>();

    public void cadastrar(){

    }

    public static void main(String[] args){
        App app = new App();

        app.cadastrar();
    }
}
