/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    static void main() {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ").toLowerCase();

        switch (mes){
            case "janeiro", "fevereiro":
                IO.println("Verão");
                break;
            case "março":
                if (dia <=20){
                    IO.println("Verão");
                }else {
                    IO.println("Outono");
                }
                break;
            case "abril", "maio":
                IO.println("Outono");
                break;
            case "junho":
                if (dia <=21){
                    IO.println("Outono");
                }else {
                    IO.println("Inverno");
                }
                break;
            case "julho", "agosto":
                IO.println("Inverno");
                break;
            case "setembro":
                if (dia <=22){
                    IO.println("Inverno");
                }else {
                    IO.println("Primavera");
                }
                break;
            case "outubro", "novembro":
                IO.println("Primavera");
                break;
            case "dezembro":
                if (dia <=21){
                    IO.println("Primavera");
                }else {
                    IO.println("Verão");
                }
                break;
        }
    }
}
