/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    private Pessoa[] vetor = new Pessoa[100];
    public void menu(){
        String msg = """
                1 - Cadastrar Pessoas
                2 - Listar todas pessoas (montar tabela invocando getters)
                3 - Imprimir dados de uma pessoa (invocar toString)
                4 - Sair
                """;
        IO.println(msg);

        while(true){
            IO.println(msg);
            int escolha = Integer.parseInt(IO.readln());
            switch(escolha){
            }

        }
    }
    // Entre com a opção; 1
    // switch


    public static void main(String[] args) {
        // id é estático, logo é atributo da classe
        App app = new App();
        app.menu();

        // | 00001 | Juca |
        // | 00010 | Ana |
        // | 00100 | Joao Pedro |

        //String s = String.format("| %05d | %30s |", id, nome);

    }
}
