/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args){
        Caneta a = new Caneta(50, "azul");
        Caneta b = new Caneta(50); // 50, azul
        Caneta c = new Caneta(); // 100, azul
        IO.println(a);

        System.out.printf("Nivel de tinta apos desenhar: %.4f%n", a.desenhar(1,1,216,321));
    }
}
