/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        String[] vetor = new String[100];
        ArrayList<String> lista = new ArrayList<>();

        lista.add("POO");
        lista.add("ADS");
        lista.add("IFSC");
        lista.add(1, "SJE");

        // for i
        for (int i = 0; i < lista.size(); i++) {
            IO.println(lista.get(i));

        }

        // for each
        for(String e : lista){
            IO.println(e);
        }

        // Utilizando o metodo forEach do ArrayList
        lista.forEach(e -> IO.println(e));

        //method reference
        lista.forEach(IO::println);

        //removendo do arraylist
        lista.removeIf(e->e.equals("ADS"));

        ArrayList<Pessoa> agenda = new ArrayList<>();

        agenda.add(new Pessoa("Juca", "juca@example.org"));
        agenda.add(new Pessoa("Ana", "ana@example.org"));
        agenda.add(new Pessoa("Pedro", "pedro@example.org"));
        agenda.add(new Pessoa("Juca", "juca@example.org"));

        agenda.removeIf( p -> p.getNome().equals("Juca"));

        agenda.forEach(IO::println);

    }
}
