/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    public static void main(String[] args) {
        String[] vetor = new String[100];
        ArrayList<String> lista = new ArrayList<>();

        lista.add("POO");
        lista.add("ADS");
        lista.add("IFSC");
        lista.add(1, "SJE");

        // for i
        for (int i = 0; i < lista.size(); i++) {
            IO.println(lista.get(i));

        }

        // for each
        for(String e : lista){
            IO.println(e);
        }

        // Utilizando o metodo forEach do ArrayList
        lista.forEach(e -> IO.println(e));

        //method reference
        lista.forEach(IO::println);

        //removendo do arraylist
        lista.removeIf(e->e.equals("ADS"));

        ArrayList<Pessoa> agenda = new ArrayList<>();

        agenda.add(new Pessoa("Juca", "juca@example.org"));
        agenda.add(new Pessoa("Ana", "ana@example.org"));
        agenda.add(new Pessoa("Pedro", "pedro@example.org"));
        agenda.add(new Pessoa("Juca", "juca@example.org"));

        agenda.removeIf( p -> p.getNome().equals("Juca"));

        agenda.forEach(IO::println);

        //(chave, valor) mapeamento da chave para o valor
        //chave é o indice para chegar no valor
        //chave é única na coleção

        HashMap<String, String> mapa = new HashMap<>();

        //HashMap<String, Pessoa> mapa = new HashMap<>();
        //mapa.put("123", new Pessoa("Juca", "juca@example.org"));


        mapa.put("123", "Juca");
        mapa.put("456", "Ana");
        mapa.put("789", "Pedro");
        mapa.put("789", "Paulo");

        String nome = mapa.get("456");

        //String nome = mapa.get("888");

        if (nome == null) {
            IO.println("Valor não encontrado. ");
        } else {
            IO.println(nome);
        }


        //Maneira mais consiza de percorrer o HashMap
        mapa.forEach((chave, valor)-> IO.println("chave: " + chave + ", valor: " + valor));

        //Outra maneira de Percorrer o HashMap
        for (var elemento : mapa.entrySet()){
            IO.println("chave: " + elemento.getKey());
            IO.println("valor: " + elemento.getValue());
        }

        mapa.remove("456"); // remoção pela chave

        mapa.values().removeIf(v->v.equals("Juca")); // remove todos com valor igual
        // Juca

    }
}
