/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args){
        Carro ferrari = new Carro();

        ferrari.acelerar(90);
        ferrari.acelerar(20);

        IO.println(ferrari.obterVelocidadeAtual());


    }


}
